/* Données neutres (non traduites) + dictionnaire de traduction complet FR/EN. */

const PROJECTS = [
  {
    id: "tbg",
    img: "assets/tbg-paysagiste.png",
    url: "https://tbg-paysagiste.vercel.app/",
  },
  {
    id: "kami",
    img: "assets/kami-auto-garage.png",
    url: "https://kami-auto-garage.vercel.app/index.html",
  },
  {
    id: "lotus",
    img: "assets/lotus-imperial.png",
    url: "https://delice-de-manille.vercel.app/",
  },
  {
    id: "plomberie",
    img: "assets/plomberie-pro.png",
    url: "https://designhandoffplomberiepro.vercel.app/",
  },
];

const SERVICES_META = [
  { num: "01", icon: "◈", pointColor: "#666666" },
  { num: "02", icon: "◎", pointColor: "#999999" },
  { num: "03", icon: "◉", pointColor: "#666666" },
];

const I18N = {
  fr: {
    nav: { home: "Accueil", projects: "Projets", services: "Services", contact: "Contact" },
    footer: {
      tagline: "Sites web sur mesure et SEO local pour propulser votre entreprise au Québec.",
      pages: "Pages",
      contactTitle: "Contact",
    },
    hero: {
      badge: "SEO Local · Québec",
      titleMain: "Refonte & création de sites web, SEO local & Google My Business — ",
      titleAccent: "votre visibilité, c'est mon métier.",
      subtitle: "Gabriel Rakoto — Créateur de sites web & spécialiste SEO local pour les entreprises du Québec.",
      ctaLabel: "TRAVAILLONS ENSEMBLE",
      cardLine1: "PME QUÉBÉCOISES",
      cardLine2: "RÉSULTATS RÉELS.",
      cta: "Travaillons ensemble →",
    },
    aboutLabel: "À propos",
    about: {
      available: "Disponible",
      bio: "Passionné par le web et le marketing local, j'accompagne les PME québécoises à construire une présence en ligne qui génère de vrais résultats. Je m'occupe du site et du référencement — vous gagnez du temps et des clients.",
      values: ["Design web", "SEO Local", "Google My Business", "Québec"],
      stats: [
        { value: "10+", label: "Projets livrés" },
        { value: "3+", label: "Ans d'expérience" },
        { value: "100%", label: "Clients locaux" },
      ],
    },
    servicesLabel: "Services",
    projectsLabel: "Projets",
    seeServices: "Voir tous les services →",
    seeProjects: "Voir tous les projets",
    seeProject: "Voir le projet",
    visit: "Visiter →",
    projectsHero: "Réalisations.",
    servicesHero: "Ce que\nje fais.",
    ctaBanner: "Prêt à dominer\nGoogle dans\nvotre ville?",
    servicesCta: "Commencer",
    projectsCta: "Un projet en tête? Parlons-en et trouvons la meilleure approche pour votre entreprise.",
    contactLabel: "04 — Contact",
    services: [
      {
        title: "Site web professionnel",
        price: "500 $",
        desc: "Un site rapide, moderne et optimisé pour convertir vos visiteurs en clients.",
        points: [
          "Design sur mesure",
          "Responsive mobile-first",
          "Hébergement 1 an inclus",
          "Formulaire de contact optimisé",
          "SEO technique de base",
        ],
      },
      {
        title: "SEO Local + GMB",
        price: "150 $/mois",
        desc: "Apparaissez en tête des recherches locales et attirez plus de clients dans votre région.",
        points: [
          "Optimisation fiche GMB",
          "Citations locales (annuaires)",
          "Mots-clés géolocalisés",
          "Rapport mensuel détaillé",
          "Suivi du positionnement",
        ],
      },
      {
        title: "Site Web + SEO Local",
        price: "500 $ + 150 $/mois",
        desc: "Site professionnel et référencement local combinés pour dominer votre marché.",
        points: [
          "Tout inclus dans les 2 offres",
          "Priorité de support",
          "Stratégie de contenu local",
          "Analyse de la concurrence",
          "Suivi mensuel personnalisé",
        ],
      },
    ],
    projects: [
      {
        tag: "Réalisation",
        title: "TBG Paysagiste",
        niche: "Aménagement paysager · Québec, QC",
        desc: "Création du site web complet pour un paysagiste spécialisé en aménagement extérieur, embellissement de piscines et espaces de rêve dans la région de Québec.",
        services: ["Site web", "SEO Local", "GMB"],
      },
      {
        tag: "Réalisation",
        title: "Kami Auto Garage",
        niche: "Garage auto · Laval, QC",
        desc: "Refonte complète du site web et campagne SEO local pour un garage automobile indépendant.",
        services: ["Site web", "SEO Local", "GMB"],
      },
      {
        tag: "Réalisation",
        title: "Lotus Impérial",
        niche: "Restaurant philippin · Montréal, QC",
        desc: "Création du site web pour un restaurant de cuisine philippine familiale, avec menu en ligne et réservations.",
        services: ["Site web", "SEO Local", "GMB"],
      },
      {
        tag: "Réalisation",
        title: "Plomberie Pro",
        niche: "Plomberie · Québec, QC",
        desc: "Création du site web pour un plombier offrant un service d'urgence 24/7, avec demande de soumission en ligne.",
        services: ["Site web", "SEO Local", "GMB"],
      },
    ],
    contact: {
      title: "Parlons de\nvotre projet.",
      subtitle: "Décrivez votre projet et je vous réponds dans les 24 heures. Pas de prise de tête, juste une vraie conversation.",
      namePlaceholder: "Votre nom",
      emailPlaceholder: "Votre email",
      messagePlaceholder: "Parlez-moi de votre projet...",
      submit: "Envoyer →",
      calendly: "📅  Réserver un appel gratuit",
      orText: "ou",
      successTitle: "Message envoyé !",
      successMsg: "Je vous réponds dans les 24 heures.",
      emailLabel: "Email",
      phoneLabel: "Téléphone",
      linkedinLabel: "LinkedIn",
    },
  },
  en: {
    nav: { home: "Home", projects: "Projects", services: "Services", contact: "Contact" },
    footer: {
      tagline: "Custom websites and local SEO to grow your business in Quebec.",
      pages: "Pages",
      contactTitle: "Contact",
    },
    hero: {
      badge: "Local SEO · Quebec",
      titleMain: "Website design, local SEO & Google My Business — ",
      titleAccent: "your visibility is my craft.",
      subtitle: "Gabriel Rakoto — Web creator & local SEO specialist for Quebec businesses.",
      ctaLabel: "LET'S WORK TOGETHER",
      cardLine1: "LOCAL BUSINESSES",
      cardLine2: "REAL RESULTS.",
      cta: "Let's work together →",
    },
    aboutLabel: "About",
    about: {
      available: "Available",
      bio: "Passionate about web and local marketing, I help Quebec SMEs build an online presence that generates real results. I handle the website and SEO — you save time and gain customers.",
      values: ["Web Design", "Local SEO", "Google My Business", "Québec"],
      stats: [
        { value: "10+", label: "Projects delivered" },
        { value: "3+", label: "Years of experience" },
        { value: "100%", label: "Local clients" },
      ],
    },
    servicesLabel: "Services",
    projectsLabel: "Projects",
    seeServices: "View all services →",
    seeProjects: "View all projects",
    seeProject: "View project",
    visit: "Visit →",
    projectsHero: "Projects.",
    servicesHero: "What\nI do.",
    ctaBanner: "Ready to rank first\non Google\nin your city?",
    servicesCta: "Get started",
    projectsCta: "Have a project in mind? Let's talk and find the best approach for your business.",
    contactLabel: "04 — Contact",
    services: [
      {
        title: "Professional Website",
        price: "$500",
        desc: "A fast, modern website optimized to convert your visitors into customers.",
        points: [
          "Custom design",
          "Mobile-first responsive",
          "1-year hosting included",
          "Optimized contact form",
          "Basic technical SEO",
        ],
      },
      {
        title: "Local SEO + GMB",
        price: "$150/mo",
        desc: "Rank at the top of local searches and attract more customers in your area.",
        points: [
          "GMB profile optimization",
          "Local citations (directories)",
          "Geolocalized keywords",
          "Detailed monthly report",
          "Ranking tracking",
        ],
      },
      {
        title: "Website + Local SEO",
        price: "$500 + $150/mo",
        desc: "Professional website and local SEO combined to dominate your market.",
        points: [
          "Everything in both offers",
          "Priority support",
          "Local content strategy",
          "Competitor analysis",
          "Monthly personalized follow-up",
        ],
      },
    ],
    projects: [
      {
        tag: "Project",
        title: "TBG Paysagiste",
        niche: "Landscaping · Québec, QC",
        desc: "Full website creation for a landscaping specialist focused on exterior design, pool beautification and outdoor spaces in the Québec region.",
        services: ["Website", "Local SEO", "GMB"],
      },
      {
        tag: "Project",
        title: "Kami Auto Garage",
        niche: "Auto Garage · Laval, QC",
        desc: "Full website redesign and local SEO campaign for an independent auto garage.",
        services: ["Website", "Local SEO", "GMB"],
      },
      {
        tag: "Project",
        title: "Lotus Impérial",
        niche: "Filipino Restaurant · Montréal, QC",
        desc: "Website creation for a family-style Filipino restaurant, with online menu and reservations.",
        services: ["Website", "Local SEO", "GMB"],
      },
      {
        tag: "Project",
        title: "Plomberie Pro",
        niche: "Plumbing · Québec, QC",
        desc: "Website creation for a plumber offering 24/7 emergency service, with online quote requests.",
        services: ["Website", "Local SEO", "GMB"],
      },
    ],
    contact: {
      title: "Let's talk about\nyour project.",
      subtitle: "Describe your project and I'll get back to you within 24 hours. No fuss, just a real conversation.",
      namePlaceholder: "Your name",
      emailPlaceholder: "Your email",
      messagePlaceholder: "Tell me about your project...",
      submit: "Send →",
      calendly: "📅  Book a free call",
      orText: "or",
      successTitle: "Message sent!",
      successMsg: "I'll get back to you within 24 hours.",
      emailLabel: "Email",
      phoneLabel: "Phone",
      linkedinLabel: "LinkedIn",
    },
  },
};

const CONTACT_INFO = {
  email: "gabrielrakotor40@gmail.com",
  phoneDisplay: "581-979-2198",
  phoneHref: "tel:+15819792198",
  linkedinUrl: "https://www.linkedin.com/in/gabriel-rakoto-708b39351/",
  linkedinDisplay: "gabriel-rakoto",
  calendlyUrl: "https://calendly.com/gabriel-rakoto",
};
